// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/3/2026, 11:17:19 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/kimchaelin/Documents/study/chae-lin.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/chae-lin.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/chae-lin.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/chae-lin.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/chae-lin.github.io/plugins/**/*.{js,ts,mjs}","/Users/kimchaelin/Documents/study/chae-lin.github.io/composables/**/*.{js,ts,mjs}","/Users/kimchaelin/Documents/study/chae-lin.github.io/utils/**/*.{js,ts,mjs}","/Users/kimchaelin/Documents/study/chae-lin.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/chae-lin.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/chae-lin.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kimchaelin/Documents/study/chae-lin.github.io/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;